function y = preprocess(x)
%  预处理输入 x
%    This function expects an input vector x.

% Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
% Generated on: 10-May-2024 12:31:11

y = highpass(x,0.04,'Steepness',0.85,'StopbandAttenuation',60);

y = bandstop(y,[0.295 0.301],'Steepness',0.85,'StopbandAttenuation',60);

y = bandstop(y,[0.602 0.608],'Steepness',0.85,'StopbandAttenuation',60);
